name: Deploy CDK Stacks to AWS

on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Name of the CDK stack to deploy'
        required: true
        type: choice
        options:
          - S3InfraStack
          - IamEventLambdaStack

env:
  AWS_REGION: us-east-1
  CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
  CDK_DEFAULT_REGION: ${{ env.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Bootstrap CDK Environment
      run: npx cdk bootstrap aws://$CDK_DEFAULT_ACCOUNT/$CDK_DEFAULT_REGION

    - name: Synthesize CDK Stacks
      run: npx cdk synth

    - name: Deploy Specified CDK Stack
      run: npx cdk deploy ${{ github.event.inputs.stack-name }} --require-approval never
